DEFAULT_SKIP = 0
DEFAULT_TAKE = 100
# Variables for the core
LENGTH_TEMPLATE_NAME = 200
LENGTH_UPDATECONNECTOR_NAME = 200
LENGTH_PROCESS_NAME = 200
LENGTH_CHAPTER_NAME = 200
LENGTH_NOTE_NAME = 200
LENGTH_NOTE_ITEM = 200
LENGTH_FIELD_CODE = 50
LENGTH_LAST_GENERATED = 25
LENGTH_ENTITY_TYPE = 10
LENGTH_SQL_BATCH_ENTITY_TYPE = 5
LENGTH_SQL_NAME = 200
LENGTH_BATCH_NAME = 200

# Variables for the data_sources
LENGTH_FILTER_FIELD = 40
LENGTH_TYPE_SOURCE = 30
LENGTH_GETCONNECTOR_FIELD_ID = 40
LENGTH_OPERATOR = 3
LENGTH_FIELD_FILTER_VALUE = 200
LENGTH_CSV_FILE_NAME = 255
LENGTH_GETCONNECTOR_NAME = 200
LENGTH_CUSTOM_NAME = 200

# Variables for the functions
LENGTH_PARAMETER_NAME = 50
LENGTH_METHOD_NAME = 50

# Variables for the settings
LENGTH_SEND_METHOD_NAME = 30
LENGTH_ROWS_FUNCTION_NAME = 30

# Variable for the variables
LENGTH_VARIABLE_NAME = 100
LENGTH_HEX_COLOR = 16
